apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: summarization-scaler
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: summarization-server
  targetCPUUtilizationPercentage: 80
